#define VIA_QMK_RGBLIGHT_ENABLE
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define ENABLE_RGB_MATRIX_ALPHAS_MODS       //works
#define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN  //works
#define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT //works
#define ENABLE_RGB_MATRIX_BREATHING  //works
#define ENABLE_RGB_MATRIX_BAND_SAT  //works
#define ENABLE_RGB_MATRIX_BAND_VAL  //works

#define ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT //works
#define ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL //works

#define ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT //works
#define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL //works

#define ENABLE_RGB_MATRIX_CYCLE_ALL //works

#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT //works
#define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN //works

#define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON //works

#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN //works
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL  //works
 
#define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL  //works
#define ENABLE_RGB_MATRIX_CYCLE_SPIRAL   //works
#define ENABLE_RGB_MATRIX_DUAL_BEACON    //works
#define ENABLE_RGB_MATRIX_RAINBOW_BEACON   //works
#define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS   //works
#define ENABLE_RGB_MATRIX_RAINDROPS  //works
#define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS  //works
#define ENABLE_RGB_MATRIX_HUE_BREATHING  //works
#define ENABLE_RGB_MATRIX_HUE_PENDULUM  //works
#define ENABLE_RGB_MATRIX_HUE_WAVE
#define ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#define ENABLE_RGB_MATRIX_PIXEL_RAIN
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define ENABLE_RGB_MATRIX_DIGITAL_RAIN  //shows up but does not work

#define ENABLE_RGB_MATRIX_SOLID_COLOR

#define RGB_MATRIX_KEYREACTIVE_ENABLED

#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE //works
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE  //works
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE  //works
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE  //works
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS  //works
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS  //works
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS  //works
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS  //works

#define ENABLE_RGB_MATRIX_SPLASH  //works
#define ENABLE_RGB_MATRIX_MULTISPLASH //works
#define ENABLE_RGB_MATRIX_SOLID_SPLASH //works
#define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH //works

#define TAPPING_TERM 200